### ISSUE TITLE
Evitar rotación

### ISSUE THREAD

**Issue by pabloriutort** [pabloriutort/Shadows#13]
Utilizando las físicas, el cubo principal (o protagonista) suele rotar al colisionar con una sombra. Lo ideal sería que no lo hiciera y evitar este comportamiento.
Queremos un **salto más rígido**, más adelante veremos si mediante animaciones podemos crear una sensación diferente.

**Comment by alfredoUcar** [comment]
Hecho, el cuerpo tiene un atributo para gestionar eso. 
Solo había que hacer `body:setFixedRotation(true)`

**Comment by pabloriutort** [comment]
Si tu código resuelve el issue lo puedes [cerrar con el mensaje del commit](https://help.github.com/articles/closing-issues-via-commit-messages/).

¿Tienes permisos para cerrar el issue manualmente? Si es así y crees que el issue está resuelto puede hacerlo tú mismo :smile:

**Comment by alfredoUcar** [comment]
Vale, tengo permisos para hacerlo pero lo dejé abierto para que dieras el visto bueno, lo tendré en cuenta para la próxima.
