### ISSUE TITLE
Tecla de espacio no funciona

### ISSUE THREAD

**Issue by pabloriutort** [pabloriutort/Shadows#15]
He estado jugando un poco y he observado que pulsar el espacio no funciona, aunque veo que la función está implementada en `controls.lua`:
```
if love.keyboard.isDown(" ")  or love.keyboard.isDown("w") or love.keyboard.isDown("up") then
	player.jump()
end
```
Las demás teclas funcionan bien y veo que la función es correcta.

**Comment by alfredoUcar** [comment]
Actualizando a _Super Toast_ también me falla pero por lo que veo la función no ha cambiado. Lo que si que he encontrado es que en la lista de [KeyConstant ](space) ha cambiado el código del espacio, ahora es simplemente **space**.

También me he dado cuenta que el código se puede simplificar poniendo solo la condición:
`love.keyboard.isDown("space","w","up")`

**Comment by alfredoUcar** [comment]
He aplicado los cambios que comenté y ya vuelve a funcionar como antes.
