### ISSUE TITLE
Color de escenario

### ISSUE THREAD

**Issue by alfredoUcar** [pabloriutort/Shadows#4]
Poder cambiar el color del escenario(el fondo) y que el color cambie automáticamente al color inverso.
Por ahora se puede realizar el cambio de color al pulsar una tecla concreta.

**Comment by pabloriutort** [comment]
No creo que esto sea propiamente una mejora del juego, pues se supone que es una característica que tiene que aparecer. Más bien es una tarea.

**Comment by pabloriutort** [comment]
Realizado en la función `changeColor(c)` de `Stage.lua`. Queda por definir los posibles colores, que serán los de las sombras.

Buen trabajo @alfredoUcar !
